version: '3'
networks:
  redes:
    driver: bridge
services:
  keycloak:
    container_name: keycloak
    image:  quay.io/keycloak/keycloak:21.1
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=fortaleza10*
      - KC_DB_URL=jdbc:postgresql://keycloak.cwnc4guvkvsw.us-east-1.rds.amazonaws.com:5432/keycloak
      - KC_DB_URL_PORT=5432
    ports:
      - 8080:8080
    command: start-dev
    networks:
      - redes
