version: '3.9'
networks:
  redes:
    driver: bridge
services:
  db:
    container_name: db
    image: postgres:11.2-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=senha
      - POSTGRES_USER=usuario
      - POSTGRES_DB=keycloak
    ports:
      - 5432:5432
    networks:
      - redes  
  keycloak:
    image: jboss/keycloak:8.0.1
    container_name: keycloak
    restart: always
    environment:
      - DB_VENDOR=POSTGRES
      - DB_ADDR=postgres
      - DB_PORT=5432
      - DB_SCHEMA=public
      - DB_DATABASE=keycloak
      - DB_USER=usuario
      - DB_PASSWORD=senha
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    depends_on:
      - db  
    networks:
      - redes
