version: '3'
networks:
  redes:
    driver: bridge
services:
  db:
    container_name: postgres
    image: postgres:11.2-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=senha
      - POSTGRES_USER=usuario
      - POSTGRES_DB=keycloak
    volumes:
      - ./postgres:/var/lib/postgresql/data/pgdata 
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      - redes  
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:19.0.1
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=password
      - KC_DB=postgres
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USERNAME=usuario
      - KC_DB_PASSWORD=senha
      - KC_DB_URL_HOST=postgres
      - KC_DB_URL_PORT=5432
    ports:
      - 8080:8080
    command: start-dev
    depends_on:
      - db  
    networks:
      - redes
